# Generated by Django 2.1.2 on 2018-11-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCd',
            fields=[
                ('task_cd', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='作業コード')),
                ('title', models.CharField(max_length=20, verbose_name='作業名')),
                ('description', models.CharField(blank=True, max_length=30, null=True, verbose_name='説明')),
                ('type', models.CharField(max_length=10, verbose_name='作業区分')),
            ],
        ),
    ]
