# Generated by Django 2.1.2 on 2018-10-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(1, '個'), (2, 'kg'), (3, 'm')], default=1, verbose_name='単価'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='顧客名'),
        ),
    ]
