# Generated by Django 2.1.2 on 2018-10-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20181026_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rank',
            field=models.CharField(max_length=1, verbose_name='ランク'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(default=1, verbose_name='単価'),
        ),
    ]
