# Generated by Django 2.1.2 on 2018-11-11 08:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_taskcd'),
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='作番')),
                ('title', models.CharField(max_length=255, verbose_name='案件名')),
                ('type', models.IntegerField(choices=[(1, '一括'), (2, '派遣'), (3, '保守'), (9, 'その他')], default=1, verbose_name='分類')),
                ('status', models.IntegerField(choices=[(1, 'プレ'), (2, '受注'), (3, '売上'), (9, '終番')], default=1, verbose_name='状態')),
                ('topic', models.CharField(blank=True, max_length=400, null=True, verbose_name='要点')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='作番開始日')),
                ('end_date', models.DateField(verbose_name='作番終了日')),
                ('expected_order_date', models.DateField(blank=True, null=True, verbose_name='受注予定日')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='受注日')),
                ('expected_sales_date', models.DateField(blank=True, null=True, verbose_name='売上予定日')),
                ('sales_date', models.DateField(blank=True, null=True, verbose_name='売上日')),
                ('expected_price', models.IntegerField(default=0, verbose_name='予想金額')),
                ('order_price', models.IntegerField(blank=True, null=True, verbose_name='受注金額')),
                ('sales_price', models.IntegerField(blank=True, null=True, verbose_name='売上金額')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.Customer', verbose_name='顧客名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='集計部門')),
                ('members', models.ManyToManyField(blank=True, related_name='member_projects', to=settings.AUTH_USER_MODEL, verbose_name='案件メンバー')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='案件担当者')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(default=datetime.datetime.now, verbose_name='作業日')),
                ('work_hour', models.IntegerField(default=0, verbose_name='作業時間')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Project', verbose_name='作番')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.TaskCd', verbose_name='作業コード')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='社員')),
            ],
            options={
                'db_table': 'project_record',
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='作業名')),
                ('man_hour', models.IntegerField(default=0, verbose_name='工数')),
                ('price', models.IntegerField(default=0, verbose_name='金額')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='作番')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task', to='master.TaskCd', verbose_name='作業コード')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'db_table': 'project_task',
            },
        ),
    ]
